os_algorithm: bdmatch
save_dir: ./saved_models/classic_cv_os
save_name: bdmatch_imagenet30_20_p1_1
resume: True
load_path: ./saved_models/classic_cv_os/bdmatch_imagenet30_20_p1_1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_log_iter: 256
batch_size: 32
eval_batch_size: 128
hard_label: True
T: 0.5
ulb_loss_ratio: 1.0
uratio: 1
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: imagenet30
train_sampler: RandomSampler
num_classes: 20
ood_test: True
labeled_percent: p1
ulb_purified: False
OOD_threshold: 0.5
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10005
dist_backend: nccl
gpu: None
p_cutoff_pos: 0.99
p_cutoff_neg: 0.01
ema_p: 0.999
tau: 0.5
use_rot: True
